services:
  postgres:
    hostname: postgres
    image: postgres:${POSTGRES_VERSION:-16-alpine}
    restart: unless-stopped
    user: "${UID:-70}:${GID:-70}"
    environment:
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./certs:/certs
      - ./initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  data:
  certs:
  initdb:
