services:
  modbus2mqtt:
    image: ghcr.io/modbus2mqtt/modbus2mqtt:${MODBUS2MQTT_VERSION:-latest}
    restart: unless-stopped
    user: "${UID:-999}:${GID:-999}"
    environment:
      TZ: ${TZ:-Europe/Berlin}
    volumes:
      - ./data:/app/data
    ports:
      - "${MODBUS2MQTT_PORT:-3000}:3000"

volumes:
  data:
