services:
  postgrest:
    image: postgrest/postgrest:${POSTGREST_VERSION:-latest}
    network_mode: host
    restart: unless-stopped
    environment:
      PGRST_DB_URI: "postgres://postgres:{{ POSTGRES_PASSWORD }}@{{ POSTGRES_HOST }}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}"
      PGRST_DB_SCHEMAS: ${PGRST_SCHEMAS:-public}
      PGRST_DB_ANON_ROLE: postgres
      PGRST_JWT_SECRET: "{{ JWT_SECRET }}"
      PGRST_SERVER_PORT: 3000
    ports:
      - "3000:3000"
